version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: forumdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "7061:7061"    


  frontend:
    build:
      context: ./Webapp
      dockerfile: Dockerfile
    ports:
      - "5137:5137"
